# Settings for Ruff (instead of autopep8) linter and formatter
# Documentatin - https://docs.astral.sh/ruff/configuration/

[lint]
# On top of the defaults (`E4`, E7`, `E9`, and `F`), enable flake8-bugbear (`B`) and flake8-quotes (`Q`).
# select = ["E4", "E7", "E9", "F", "B", "Q"]
# select = ["E4", "E7", "E9", "F", "B", "Q", "DJ"]
# select = ["E", "W", "N", "D", "F", "B", "Q", "BLE", "FBT", "COM", "UP", "ANN"]
select = ["E4", "E7", "E9", "F", "B", "Q", "DJ"]