# syntax=docker/dockerfile:1

FROM node:current-alpine as base
ENV APP_ROOT /app
ENV NODE_ENV development

WORKDIR ${APP_ROOT}
# ADD . ${APP_ROOT}

FROM base as build

COPY ./frontend/package-lock.json ${APP_ROOT}
COPY ./frontend/package.json ${APP_ROOT}

RUN npm ci
# RUN npm run build

# CMD ["npm", "run", "start"]

FROM base

COPY --from=build ${APP_ROOT}/node_modules ${APP_ROOT}/node_modules

# CMD [ "npm", "run", "dev" ]